apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Values.resourceNamePrefix }}-post-delete-service-account
  namespace: {{ .Release.Namespace }}