apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Values.resourceNamePrefix }}-post-delete-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        {{- with .Values.pod.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.pod.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      containers:
      - args: [
          "release-post-delete",
          "--api-key-token-file-path",
          "/var/run/secrets/application/apikeytoken",
          "--api-url",
          {{ .Values.apiUrl | quote }},
          "--helm-release-name",
          {{- print .Release.Namespace ":" .Release.Name | quote }},
          {{- if .Values.proxyUrl }}
          "--proxy-url",
          {{ .Values.proxyUrl | quote }},
          {{- end}}
        ]
        {{- include "environmentVariables" . | nindent 8 }}
        image: {{ include "containerImagePath" . }}
        imagePullPolicy: Always
        name: {{ .Values.resourceNamePrefix }}-post-delete-container
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: {{ .Values.resourceNamePrefix }}-post-delete-secret
          mountPath: "/var/run/secrets/application"
          readOnly: true
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
        runAsUser: 1000
        {{- end }}
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.containerImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.resourceNamePrefix }}-post-delete-service-account
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- include "apiKeyTokenVolume" (dict "name" (print .Values.resourceNamePrefix "-post-delete-secret") "root" .) | nindent 6 }}
---
{{ $annotations := 
  list 
  "helm.sh/hook: post-delete"
  "helm.sh/hook-delete-policy: hook-failed, before-hook-creation, hook-succeeded"
  "helm.sh/hook-weight: \"-1\"" }}
{{ include "apiKeyTokenSecret" (dict "name" (print .Values.resourceNamePrefix "-post-delete-secret") "root" . "annotations" $annotations) }}