{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "agent.labels" . | nindent 4 }}
  name: {{ include "agent.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}