apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation, hook-succeeded
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Values.resourceNamePrefix }}-pre-install-job
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        {{- with .Values.pod.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- with .Values.pod.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args: [
          "release-pre-install",
          "--api-key-token-file-path",
          "/var/run/secrets/application/apikeytoken",
          "--api-url",
          {{ .Values.apiUrl | quote }},
          "--application-version",
          {{ .Chart.AppVersion | quote }},
          "--helm-release-name",
          {{ print .Release.Namespace ":" .Release.Name | quote }},
          {{- if .Values.name }}
          "--name",
          {{ .Values.name | quote }},
          {{- end}}
          {{- if .Values.proxyUrl }}
          "--proxy-url",
          {{ .Values.proxyUrl | quote }},
          {{- end}}
          {{- if .Values.accountId }}
          "--tenant-raw-id",
          {{ .Values.accountId | quote }}
          {{- end}}
        ]
        {{- include "environmentVariables" . | nindent 8 }}
        image: {{ include "containerImagePath" . }}
        imagePullPolicy: Always
        name: {{ .Values.resourceNamePrefix }}-pre-install-container
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: {{ .Values.resourceNamePrefix }}-pre-install-secret
          mountPath: "/var/run/secrets/application"
          readOnly: true
      {{- with .Values.containerImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
        runAsUser: 1000
        {{- end }}
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ .Values.resourceNamePrefix }}-pre-install-service-account
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- include "apiKeyTokenVolume" (dict "name" (print .Values.resourceNamePrefix "-pre-install-secret") "root" .) | nindent 6 }}
---
{{ $annotations :=
  list
  "helm.sh/hook: pre-install, pre-upgrade"
  "helm.sh/hook-delete-policy: hook-failed, before-hook-creation, hook-succeeded" 
  "helm.sh/hook-weight: \"-1\"" }}
{{ include "apiKeyTokenSecret" (dict "name" (print .Values.resourceNamePrefix "-pre-install-secret") "root" . "annotations" $annotations) }}