apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.resourceNamePrefix" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "updater.resourceNamePrefix" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "updater.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}