apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "updater.labels" . | nindent 4 }}
  name: {{ include "updater.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}