{{- if .Values.connector.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "connector.labels" . | nindent 4 }}
  name: {{- include "connector.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}
{{- end }}