apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "manager.labels" . | nindent 4 }}
  name: {{ include "manager.globalResourceName" (dict "name" "cr" "root" .) }}
rules:
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["get"]