apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- include "manager.labels" . | nindent 4 }}
  name: {{ include "manager.resourceNamePrefix" . }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "manager.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.pod.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "labels" . | nindent 8 }}
        {{- include "manager.labels" . | nindent 8 }}
        {{- with .Values.pod.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.pod.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      containers:
      - args: [
          "manager",
          "--api-key-token-file-path",
          "/var/run/secrets/application/apikeytoken",
          "--api-url",
          {{ .Values.apiUrl | quote }},
          "--application-version",
          {{ .Chart.AppVersion | quote }},
          "--helm-release-name",
          {{ print .Release.Namespace ":" .Release.Name | quote }},
          "--image-pull-secret-name",
          {{ print .Values.resourceNamePrefix "-image-pull-secret" | quote }},
          {{- if .Values.name }}
          "--name",
          {{ .Values.name | quote }},
          {{- end}}
          {{- if .Values.proxyUrl }}
          "--proxy-url",
          {{ .Values.proxyUrl | quote }},
          {{- end}}
          {{- if .Values.accountId }}
          "--tenant-raw-id",
          {{ .Values.accountId | quote }}
          {{- end}}
        ]
        {{- include "environmentVariables" . | nindent 8 }}
        image: {{ .Values.containerImagePath }}
        imagePullPolicy: Always
        name: {{ include "manager.resourceNamePrefix" . }}-container
        {{- with .Values.pod.resources }}
        resources:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          {{- if not (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") }}
          runAsUser: 1000
          {{- end }}
        volumeMounts:
        - name: {{ .Values.resourceNamePrefix }}-secret
          mountPath: "/var/run/secrets/application"
          readOnly: true
      {{- with .Values.containerImagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "manager.resourceNamePrefix" . }}-service-account
      {{- with .Values.pod.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- include "apiKeyTokenVolume" (dict "name" (print .Values.resourceNamePrefix "-secret") "root" .) | nindent 6 }}