apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- include "annotations" . | nindent 4 }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
    {{- include "labels" . | nindent 4 }}
  name: {{- include "manager.resourceNamePrefix" . }}-service-account
  namespace: {{ .Release.Namespace }}